### ISSUE TITLE
[S1 - PBI01] Membuat Halaman Registrasi

### ISSUE THREAD

**Issue by mhdanpi** [SI-RPL-2022/SI4301_G_KARRIR#1]
Sebagai pengguna website, saya ingin melakukan registrasi untuk membuat akun di website KARRIR.COM sehingga saya dapat mengakses seluruh fitur yang terdapat dalam website

Halaman registrasi pengguna
![image](https://user-images.githubusercontent.com/92258273/172780797-23eba7e4-07af-433f-80dc-a8246309b486.png)

**Comment by mhdanpi** [comment]
![image](https://user-images.githubusercontent.com/92258273/163726709-8eff489f-4516-4ec8-8bb0-913c58475fb8.png)

**Comment by tienfkusumasari** [comment]
Pada saat review spritn 1 form sudah terbuat dan db jug sudah di buat tapi belum tersambungkan ke database
