### ISSUE TITLE
[S1 - PBI19] Membuat fitur logout

### ISSUE THREAD

**Issue by yolafidya** [SI-RPL-2022/SI4301_G_KARRIR#7]
Sebagai Pelamar kerja dan admin, saya ingin keluar dari website KARRIR.COM sehingga saya dapat memastikan informasi diri dan data saya aman.

logout Admin
![Logout Admin](https://user-images.githubusercontent.com/92252728/164458307-235c7755-ee26-4617-9b80-31f7b50bdcc3.png)

**Comment by tienfkusumasari** [comment]
done(SP2)
